.TH nt 1
.SH NAME
.PP
nt  \- simple note taker
.SH SYNOPSIS
.PP
\fB\fCnt\fR [\-lv] [\-f \fIFILE\fP] [\-d \fINOTE\fP] [\-s \fISEARCH\fP] [\-n \fINUM\fP | \-\fINUM\fP] [\fINOTE\fP ...]
.SH DESCRIPTION
.PP
Simple note taker for the command line.
.SH OPTIONS
.PP
\-v
    Print version info and exit
.PP
\-f \fIFILE\fP
    Load \fIFILE\fP instead of default one
.PP
\-l
    List notes
.PP
\-n \fINUM\fP
    List last \fINUM\fP notes
.PP
\-s \fISEARCH\fP
    Search for \fISEARCH\fP in notes
.PP
\-d \fINOTE\fP
    Delete \fINOTE\fP from notes
.SH AUTHOR
.PP
Ed van Bruggen \<edvb54@gmail.com\>
.SH SEE ALSO
.PP
View source code at: \<https://gitlab.com/edvb/nt\>
.SH LICENSE
.PP
zlib License
