.TH nt 1
.SH NAME
.PP
nt  \- simple note taker
.SH SYNOPSIS
.PP
\fB\fCnt\fR [\fB\-Dlvy\fP] [\fB\-f\fP \fIFILE\fP] [\fB\-e\fP \fINOTE\fP] [\fB\-d\fP \fINOTE\fP] [\fB\-s\fP \fISEARCH\fP] [\fB\-t\fP [\fITAG\fP]] [\fB\-n\fP \fINUM\fP | \fB\-NUM\fP] [\fINOTE\fP ...]
.SH DESCRIPTION
.PP
Simple note taker for the command line. To take a note simply run the command
with the new note as arguments or from stdin. The note will be saved to a plain
text file with each line being a note. The file is saved to the file either
specified with \fB\-f\fP or in the default one from \fB\fCconfig.h\fR\&. Notes can have tags
by prefixing the note with a tag followed by a colon. For example a note
\fB\fCchores: take out trash\fR will have the tag \fB\fCchores\fR\&.
.SH OPTIONS
.PP
\fB\-d\fP \fINOTE\fP
    Delete \fINOTE\fP from notes
.PP
\fB\-D\fP
    Delete all notes from \fIFILE\fP
.PP
\fB\-e\fP \fINOTE\fP
    Edit \fINOTE\fP with new text given through stdin
.PP
\fB\-f\fP \fIFILE\fP
    Load \fIFILE\fP instead of default one
.PP
\fB\-l\fP
    List notes
.PP
\fB\-n\fP \fINUM\fP, \fB\-NUM\fP
    List last \fINUM\fP notes
.PP
\fB\-s\fP \fISEARCH\fP
    Search for pattern \fISEARCH\fP in notes
.PP
\fB\-t\fP [\fITAG\fP]
    Search for \fITAG\fP in notes, list all tags if no \fITAG\fP is given
.PP
\fB\-v\fP
    Print version info and exit
.PP
\fB\-y\fP
    Auto reply yes to confirmation prompts
.SH USAGE
.PP
Add simple note and list it:
.PP
.RS
.nf
$ nt clean dishes
$ nt \-l
clean dishes
.fi
.RE
.PP
Create note in specified file:
.PP
.RS
.nf
$ nt \-f list take out trash
$ nt \-f list \-l
take out trash
.fi
.RE
.PP
Add more notes by running command again:
.PP
.RS
.nf
$ nt wash car
$ nt \-l
clean dishes
wash car
$ nt buy pie
$ nt \-l
clean dishes
wash car
buy pie
.fi
.RE
.PP
List just the \fINUM\fP most recent notes:
.PP
.RS
.nf
$ nt \-1
buy pie
$ nt \-n 1
buy pie
$ nt \-2
buy pie
wash car
$ nt \-n 2
buy pie
wash car
.fi
.RE
.PP
Search notes with a specified term:
.PP
.RS
.nf
$ nt \-s pie
buy pie
$ nt make pie
$ nt \-s pie
buy pie
make pie
.fi
.RE
.PP
Remove given note:
.PP
.RS
.nf
$ nt \-yd buy pie
$ nt \-l
clean dishes
wash car
make pie
.fi
.RE
.PP
Edit note with new text given from stdin:
.PP
.RS
.nf
$ echo eat pie | nt \-e make pie
$ nt \-l
clean dishes
wash car
eat pie
.fi
.RE
.PP
Remove all notes:
.PP
.RS
.nf
$ nt \-yD
$ nt \-l
$ nt \-f list \-yD
$ nt \-f list \-l
.fi
.RE
.SH AUTHOR
.PP
Ed van Bruggen 
\<edvb54@gmail.com\>
.SH SEE ALSO
.PP
View source code at: 
\<https://gitlab.com/edvb/nt\>
.SH LICENSE
.PP
zlib License
